# This belongs in iter8-kfserving. Moving it there ...
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: kfserving
  labels:
    iter8-domain: iter8-kfserving
spec:
  namespaceSelector:
    any: true
  selector:
    matchLabels:
      networking.internal.knative.dev/serviceType: Private
  endpoints:
  - port: http-usermetric
    interval: 15s